mercury_app/config/routes.rb
Rails.application.routes.draw do
  mount Mercury::Engine => '/'
  scope '(:locale)' do
    resources :articals 
  end

  root to: 'articals#index'
end

mercury_app/app/models/artical.rb
class Artical < ActiveRecord::Base
end

mercury_app/app/models/page.rb
class Page < ActiveRecord::Base
end

mercury_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

mercury_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

mercury_app/app/controllers/articals_controller.rb
class ArticalsController < ApplicationController

  def index
    @articals = Artical.all
  end


  def show
    @artical = Artical.find(params[:id])
  end

  def update
    artical = Artical.find(params[:id])
    artical.title = params[:content][:page_title][:value]
    artical.content = params[:content][:page_content][:value]
    artical.save!
    render text: ''
  end
end

mercury_app/app/helpers/application_helper.rb
module ApplicationHelper
end

mercury_app/app/helpers/pages_helper.rb
module PagesHelper
end

mercury_app/app/views/articals/index.html.erb
<table>
	<th>Author</th>
	<th>Publisher</th>
	<th>Title</th>
	<th>Action</th>
	<%@articals.each do |artical|%>
		<tr>
			<td><%=artical.auth_name%></td>
			<td><%=artical.publication_name%></td>
			<td><%=artical.title%></td>
			<td><%=link_to "View", artical_path(artical)%></td>
		</tr>
	<%end%>
</table>

mercury_app/app/views/articals/show.html.erb
<h1 data-mercury="simple" id="page_title"><%= @artical.title.html_safe %></h1>
<div data-mercury="full" id="page_content"><%= @artical.content.html_safe if @artical.content%></div>
<p>
	<%= link_to "Edit Page View", "/editor" + request.path, id: "edit_page"%>
	<%= link_to "Back To List", "/", id: "back_to_list"%>
</p>


<script type="text/javascript">
	$("#rotate").click(function(){
		alert("U'll get more informtion about this as you scroll down")
	})
</script>

mercury_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MercuryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

mercury_app/app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>